AWSTemplateFormatVersion: '2010-09-09'
Description: trellomatic
Globals:
  Function:
    Timeout: 20
Outputs:
  EndRetroApi:
    Description: API Gateway endpoint URL for Prod stage for End Retro function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/end-retro/
  EndRetroFunction:
    Description: End Retro Lambda Function ARN
    Value:
      Fn::GetAtt:
      - EndRetroFunction
      - Arn
  EndRetroFunctionIamRole:
    Description: Implicit IAM Role created for End Retro function
    Value:
      Fn::GetAtt:
      - EndRetroFunctionRole
      - Arn
  StartRetroApi:
    Description: API Gateway endpoint URL for Prod stage for End Retro function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/start-retro/
Resources:
  EndRetroFunction:
    Properties:
      CodeUri: s3://trellomatic-bucket/de3f6b64347e92e40ea00c26d1ad4639
      Events:
        EndRetro:
          Properties:
            Method: post
            Path: /end-retro
          Type: Api
      Handler: end/EndRetro.Main
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  StartRetroFunction:
    Properties:
      CodeUri: s3://trellomatic-bucket/de3f6b64347e92e40ea00c26d1ad4639
      Events:
        StartRetro:
          Properties:
            Method: post
            Path: /start-retro
          Type: Api
      Handler: start/StartRetro.Main
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
