AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:
    trellomatic
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 20

Resources:

    EndRetroFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: end/EndRetro.Main
            Runtime: nodejs8.10
            Events:
                EndRetro:
                    Type: Api
                    Properties:
                        Path: /end-retro
                        Method: post

    StartRetroFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: start/StartRetro.Main
            Runtime: nodejs8.10
            Events:
                StartRetro:
                    Type: Api
                    Properties:
                        Path: /start-retro
                        Method: post
    
Outputs:

    StartRetroApi:
        Description: "API Gateway endpoint URL for Prod stage for End Retro function"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/start-retro/"

    EndRetroApi:
      Description: "API Gateway endpoint URL for Prod stage for End Retro function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/end-retro/"

    EndRetroFunction:
      Description: "End Retro Lambda Function ARN"
      Value: !GetAtt EndRetroFunction.Arn

    EndRetroFunctionIamRole:
      Description: "Implicit IAM Role created for End Retro function"
      Value: !GetAtt EndRetroFunctionRole.Arn
