env:
  es6: true
  node: true
  jest: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-console: 'off'
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  
